
name: tp-lab-actions
run-name: TiilS is running TPLab04
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test project
	run: cmake -H. -B_build 
	run: cmake --build _build
        run: ./.github/workflows/test.sh
